version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5431:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

volumes:
  postgres:
